# Generated by Django 6.0.5 on 2026-06-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_contato', models.CharField(choices=[('parceria', 'Parceria'), ('problema', 'Reportar Problema'), ('duvida', 'Dúvida'), ('outro', 'Outro')], max_length=20)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
